<?php

declare(strict_types=1);

namespace App\Support;

final class CatalogSeed
{
    /** @return array<string, array{nombre:string,tipo:string,items:list<string>}> */
    public static function simple(): array
    {
        return [
            'SI_NO' => ['nombre' => 'Sí/No', 'tipo' => 'SIMPLE', 'items' => ['Sí', 'No', 'No sabe', 'No aplica']],
            'ESTADO_CIVIL' => ['nombre' => 'Estado civil', 'tipo' => 'SIMPLE', 'items' => ['Soltero(a)', 'Casado(a)', 'Unión libre', 'Divorciado(a)', 'Viudo(a)', 'Separado(a)', 'Por confirmar']],
            'TIPO_SOCIEDAD' => ['nombre' => 'Tipo sociedad', 'tipo' => 'SIMPLE', 'items' => ['S.A.S.', 'S.A.', 'Ltda.', 'Empresa unipersonal', 'Persona natural', 'Fundación/ESAL', 'Otra']],
            'VINCULO_FAMILIAR' => ['nombre' => 'Tipo vínculo', 'tipo' => 'SIMPLE', 'items' => ['Fundador(a)', 'Hijo(a)', 'Nieto(a)', 'Cónyuge/compañero(a)', 'Hermano(a)', 'Otro familiar', 'No familiar']],
            'GENERACION_FAMILIAR' => ['nombre' => 'Generación familiar', 'tipo' => 'SIMPLE', 'items' => ['Primera Generación', 'Segunda Generación', 'Tercera Generación', 'No aplica', 'Por confirmar']],
            'ORIGEN_ACCIONES' => ['nombre' => 'Origen acciones', 'tipo' => 'SIMPLE', 'items' => ['Constitución', 'Compra', 'Donación', 'Herencia', 'Capitalización', 'Cesión', 'Otro', 'Adjud. Liquid. comunidad']],
            'ESTADO_DOCUMENTO' => ['nombre' => 'Estado documento', 'tipo' => 'SIMPLE', 'items' => ['Existe y está actualizado', 'Existe, requiere revisión', 'No existe', 'En preparación', 'No sabe', 'No aplica']],
            'NIVEL_RIESGO' => ['nombre' => 'Nivel riesgo', 'tipo' => 'SIMPLE', 'items' => ['Bajo', 'Medio', 'Alto', 'Crítico']],
            'NIVEL_PRIORIDAD' => ['nombre' => 'Nivel prioridad', 'tipo' => 'SIMPLE', 'items' => ['Bajo', 'Medio', 'Alto', 'Crítico']],
            'AMBITO_PATRIMONIAL' => ['nombre' => 'Ámbito patrimonial', 'tipo' => 'SIMPLE', 'items' => ['Personal', 'Familiar', 'Empresarial', 'Compartido', 'Mixto', 'No aplica', 'Por confirmar']],
            'TIPO_TITULAR' => ['nombre' => 'Tipo titular', 'tipo' => 'SIMPLE', 'items' => ['Persona natural', 'Persona jurídica', 'Sociedad familiar', 'Sociedad patrimonial', 'Patrimonio autónomo', 'Copropiedad', 'Sucesión ilíquida', 'Tercero', 'No aplica', 'Por confirmar']],
            'CLASIFICACION_PATRIMONIAL' => ['nombre' => 'Clasificación patrimonial', 'tipo' => 'SIMPLE', 'items' => ['Propio', 'Social/ganancial', 'Empresarial', 'Copropiedad', 'Pendiente de determinar']],
            'MONEDA' => ['nombre' => 'Moneda', 'tipo' => 'SIMPLE', 'items' => ['COP', 'USD', 'EUR', 'Otra', 'No aplica', 'Por confirmar']],
            'FORMA_ADQUISICION_ACTIVO' => ['nombre' => 'Forma adquisición activo', 'tipo' => 'SIMPLE', 'items' => ['Compra', 'Donación', 'Herencia', 'Aporte', 'Permuta', 'Cesión', 'Adjudicación', 'Construcción', 'Capitalización', 'Dación en pago', 'Otro', 'No aplica', 'Por confirmar']],
            'METODO_VALORACION' => ['nombre' => 'Método valoración', 'tipo' => 'SIMPLE', 'items' => ['Avalúo comercial', 'Avalúo catastral', 'Valor contable', 'Valor fiscal', 'Valor de mercado', 'Flujo de caja descontado', 'Múltiplos', 'Perito independiente', 'Estimación', 'Otro', 'No aplica', 'Por confirmar']],
            'NIVEL_LIQUIDEZ' => ['nombre' => 'Nivel liquidez', 'tipo' => 'SIMPLE', 'items' => ['Alta', 'Media', 'Baja', 'Nula', 'No aplica', 'Por confirmar']],
            'ESTADO_FISICO_ACTIVO' => ['nombre' => 'Estado físico activo', 'tipo' => 'SIMPLE', 'items' => ['Excelente', 'Bueno', 'Regular', 'Malo', 'No aplica', 'Por confirmar']],
            'ESTADO_JURIDICO_ACTIVO' => ['nombre' => 'Estado jurídico activo', 'tipo' => 'SIMPLE', 'items' => ['Libre', 'Gravado', 'Embargado', 'En litigio', 'En sucesión', 'Con restricción de transferencia', 'No aplica', 'Por confirmar']],
            'ESTADO_SOPORTE' => ['nombre' => 'Estado soporte', 'tipo' => 'SIMPLE', 'items' => ['Original localizado', 'Copia auténtica', 'Copia simple', 'Digitalizado', 'Pendiente de localizar', 'No existe', 'No aplica', 'Por confirmar']],
            'ESTADO_GESTION' => ['nombre' => 'Estado gestión', 'tipo' => 'SIMPLE', 'items' => ['Pendiente', 'En análisis', 'En trámite', 'Completado', 'Suspendido', 'No aplica', 'Por confirmar']],
            'ESTADO_DECISION' => ['nombre' => 'Estado decisión', 'tipo' => 'SIMPLE', 'items' => ['Por definir', 'Pendiente', 'En discusión', 'Aprobada', 'Implementada', 'Rechazada', 'Postergada']],
            'ESTRUCTURA_CARPETAS' => ['nombre' => 'Estructura carpetas', 'tipo' => 'SIMPLE', 'items' => ['01_Constitucion_y_existencia', '02_Libros_actas_y_organos', '03_Acciones_y_participaciones', '04_Acuerdos_y_restricciones', '05_Financiero_contable_tributario', '06_Valoraciones', '07_Inmuebles_y_activos', '08_Marcas_e_intangibles', '09_Protocolo_y_gobierno_familiar', '10_Politicas_familiares', '11_Estado_civil_y_capitulaciones', '12_Sucesiones_y_testamentos', '13_Donaciones_usufructos_y_fiducias', '14_Seguros', '15_Administracion_y_poderes', '16_Familiares_trabajadores', '17_Contratos_con_familiares', '18_Riesgos_y_litigios', '19_Conceptos_y_auditorias', '20_Implementacion_y_control']],
        ];
    }

    /** @return array<string, list<string>> */
    public static function documentGroups(): array
    {
        return [
            '01_CONSTITUCION_Y_EXISTENCIA_DE_LAS_EMPRESAS' => ['Documento de constitución de la sociedad', 'Acta de constitución', 'Estatutos sociales vigentes', 'Reforma estatutaria inicial', 'Última reforma estatutaria', 'Histórico de reformas estatutarias', 'Certificado de existencia y representación legal', 'Registro Único Tributario - RUT', 'Matrícula mercantil', 'Documento de renovación de matrícula mercantil', 'Objeto social vigente', 'Certificación de actividad económica', 'Documento de transformación societaria', 'Documento de fusión', 'Documento de escisión', 'Documento de disolución de la sociedad', 'Documento de liquidación de la sociedad'],
            '02_LIBROS_ACTAS_Y_ORGANOS_SOCIETARIOS' => ['Libro de actas de asamblea general de accionistas', 'Libro de actas de junta directiva', 'Libro de registro de accionistas', 'Actas de asamblea general de accionistas', 'Actas de reuniones extraordinarias de accionistas', 'Actas de junta directiva', 'Reglamento de la asamblea de accionistas', 'Reglamento de junta directiva', 'Acta de nombramiento de representante legal', 'Acta de nombramiento de junta directiva', 'Acta de aceptación del cargo', 'Carta de renuncia de administrador', 'Certificación de composición accionaria', 'Certificación expedida por representante legal', 'Certificación expedida por revisor fiscal'],
            '03_ACCIONES_CUOTAS_Y_PARTICIPACIONES' => ['Títulos de acciones', 'Certificados de acciones', 'Documento de suscripción de acciones', 'Reglamento de emisión y colocación de acciones', 'Documento de capitalización', 'Documento de adquisición de acciones', 'Contrato de compraventa de acciones', 'Promesa de compraventa de acciones', 'Contrato de cesión de acciones', 'Contrato de donación de acciones', 'Documento de aceptación de donación', 'Documento de transferencia de acciones', 'Documento de adjudicación de acciones', 'Registro de transferencia en el libro de accionistas', 'Soporte de pago o aporte de acciones', 'Documento de readquisición de acciones', 'Documento de cancelación de acciones', 'Documento de conversión de acciones', 'Documento de usufructo de acciones', 'Documento de nuda propiedad de acciones', 'Documento de prenda sobre acciones', 'Documento de liberación de prenda sobre acciones'],
            '04_RESTRICCIONES_NEGOCIACION_Y_ACUERDOS_ENTRE_ACCIONISTAS' => ['Acuerdo de accionistas', 'Pacto de socios', 'Autorización para negociación de acciones', 'Oferta de venta de acciones', 'Ejercicio del derecho de preferencia', 'Renuncia al derecho de preferencia', 'Opción de compra de acciones', 'Opción de venta de acciones', 'Derecho de primera oferta', 'Derecho de primera negociación', 'Acuerdo de permanencia accionaria', 'Acuerdo de voto', 'Acuerdo de sindicación de acciones', 'Acuerdo de confidencialidad entre accionistas', 'Acuerdo de no competencia', 'Restricción estatutaria a la negociación de acciones', 'Procedimiento de ingreso de nuevos accionistas', 'Procedimiento de retiro de accionistas', 'Procedimiento de compra de acciones por divorcio', 'Procedimiento de compra de acciones por fallecimiento', 'Procedimiento de compra de acciones por incapacidad'],
            '05_INFORMACION_FINANCIERA_CONTABLE_Y_TRIBUTARIA' => ['Estados financieros del último año', 'Estados financieros históricos', 'Estado de situación financiera', 'Estado de resultados', 'Estado de flujo de efectivo', 'Estado de cambios en el patrimonio', 'Notas a los estados financieros', 'Certificación de estados financieros', 'Dictamen del revisor fiscal', 'Declaración de renta de la sociedad', 'Declaraciones tributarias relevantes', 'Información exógena', 'Conciliación fiscal', 'Informe de cartera y obligaciones', 'Relación de activos y pasivos', 'Relación de contingencias judiciales', 'Relación de garantías otorgadas', 'Relación de créditos y obligaciones financieras', 'Relación de cuentas por cobrar', 'Relación de cuentas por pagar', 'Documento de cuenta por cobrar a accionista', 'Documento de cuenta por pagar a accionista', 'Informe de operaciones con vinculados', 'Informe de partes relacionadas', 'Presupuesto anual', 'Flujo de caja proyectado'],
            '06_VALORACION_DE_EMPRESAS_Y_ACCIONES' => ['Avalúo o valoración de la empresa', 'Valoración patrimonial contable', 'Valoración patrimonial ajustada', 'Valoración de acciones o participaciones', 'Valor intrínseco por acción', 'Valor comercial de acciones', 'Informe financiero de valoración', 'Valoración por flujo de caja descontado', 'Valoración por múltiplos', 'Valoración de activos', 'Valoración de intangibles', 'Valoración de marca', 'Valoración de cartera', 'Informe de perito independiente', 'Concepto de valoración', 'Metodología de valoración de acciones', 'Política de valoración y compra de acciones'],
            '07_BIENES_INMUEBLES_Y_PATRIMONIO_MATERIAL' => ['Certificado de tradición y libertad de inmueble', 'Escritura pública de adquisición de inmueble', 'Contrato de compraventa de inmueble', 'Promesa de compraventa de inmueble', 'Documento de adjudicación de inmueble', 'Avalúo comercial de inmueble', 'Avalúo catastral de inmueble', 'Recibo del impuesto predial', 'Certificado catastral', 'Contrato de arrendamiento de inmueble', 'Documento de propiedad de vehículos', 'Tarjeta de propiedad de vehículos', 'Inventario de maquinaria y equipos', 'Inventario de muebles y enseres', 'Documento de propiedad de otros activos', 'Relación de inmuebles familiares', 'Relación de inmuebles societarios', 'Relación de bienes en copropiedad', 'Documento de hipoteca', 'Documento de levantamiento de hipoteca', 'Documento de embargo', 'Documento de levantamiento de embargo'],
            '08_MARCAS_PROPIEDAD_INTELECTUAL_E_INTANGIBLES' => ['Certificado de registro de marca', 'Solicitud de registro de marca', 'Documento de propiedad de marca', 'Contrato de licencia de marca', 'Contrato de cesión de marca', 'Documento de propiedad intelectual', 'Registro de derechos de autor', 'Contrato de licencia de software', 'Contrato de cesión de derechos de autor', 'Documento de propiedad de dominio web', 'Inventario de activos intangibles', 'Valoración de marca', 'Valoración de propiedad intelectual', 'Acuerdo de confidencialidad', 'Acuerdo de protección de secretos empresariales'],
            '09_PROTOCOLO_FAMILIAR_Y_GOBIERNO_DE_LA_FAMILIA' => ['Protocolo de familia', 'Borrador del protocolo de familia', 'Acta de aprobación del protocolo de familia', 'Documento de adhesión al protocolo de familia', 'Documento de actualización del protocolo de familia', 'Acta de reunión familiar', 'Acta de Asamblea de Familia', 'Acta del Consejo de Familia', 'Reglamento del Consejo de Familia', 'Reglamento de la Asamblea de Familia', 'Árbol genealógico familiar', 'Mapa de la familia empresaria', 'Mapa societario', 'Mapa de composición accionaria', 'Mapa patrimonial', 'Matriz de riesgos familiares', 'Matriz de riesgos societarios', 'Matriz de riesgos sucesorales', 'Matriz de implementación jurídica', 'Código de ética familiar y empresarial', 'Manual de gobierno corporativo', 'Manual de administración del patrimonio familiar', 'Plan de formación de nuevas generaciones', 'Plan de comunicación familiar'],
            '10_POLITICAS_FAMILIARES_Y_EMPRESARIALES' => ['Política de empleo de familiares', 'Política de ingreso de familiares a la empresa', 'Política salarial para familiares', 'Política de evaluación de familiares', 'Política de ascenso de familiares', 'Política de retiro de familiares', 'Política de dividendos', 'Política de reinversión de utilidades', 'Política de préstamos a familiares', 'Política de ayudas familiares', 'Política de uso de bienes de la empresa', 'Política de vehículos empresariales', 'Política de gastos personales', 'Política de operaciones con partes relacionadas', 'Política de conflictos de interés', 'Política de confidencialidad', 'Política de no competencia', 'Política de solución de conflictos', 'Política de ingreso de nuevos accionistas', 'Política de retiro de accionistas', 'Política de sucesión gerencial', 'Política de sucesión accionaria', 'Política de valoración y compra de acciones', 'Política de venta de activos estratégicos', 'Política de endeudamiento', 'Política de garantías otorgadas por la empresa'],
            '11_ESTADO_CIVIL_MATRIMONIO_Y_UNION_MARITAL' => ['Registro civil de nacimiento', 'Registro civil de matrimonio', 'Registro civil de defunción', 'Documento de identidad', 'Capitulaciones matrimoniales', 'Capitulaciones maritales', 'Escritura pública de capitulaciones', 'Modificación de capitulaciones', 'Inventario anexo a capitulaciones', 'Declaración de unión marital de hecho', 'Escritura de declaración de unión marital de hecho', 'Sentencia de declaración de unión marital de hecho', 'Documento de constitución de sociedad patrimonial', 'Escritura de disolución de sociedad patrimonial', 'Escritura de liquidación de sociedad patrimonial', 'Sentencia de disolución y liquidación de sociedad patrimonial', 'Escritura de disolución de sociedad conyugal', 'Escritura de liquidación de sociedad conyugal', 'Sentencia de divorcio', 'Sentencia de separación de bienes', 'Acta de conciliación sobre bienes', 'Acuerdo patrimonial entre cónyuges', 'Acuerdo patrimonial entre compañeros permanentes', 'Inventario de bienes propios', 'Inventario de bienes sociales', 'Inventario de bienes personales', 'Certificación de estado civil'],
            '12_SUCESIONES_Y_TESTAMENTOS' => ['Testamento abierto', 'Testamento cerrado', 'Copia auténtica del testamento', 'Escritura pública de testamento', 'Modificación de testamento', 'Revocatoria de testamento', 'Inventario sucesoral', 'Trabajo de partición y adjudicación', 'Escritura de sucesión', 'Sentencia de sucesión', 'Acta de adjudicación de herencia', 'Documento de aceptación de herencia', 'Documento de repudio de herencia', 'Certificado de derechos sucesorales', 'Cesión de derechos herenciales', 'Contrato de compraventa de derechos herenciales', 'Acuerdo entre herederos', 'Documento de designación de albacea', 'Documento de aceptación del cargo de albacea', 'Documento de designación de tutor', 'Documento de designación de curador', 'Plan de sucesión accionaria', 'Plan de sucesión patrimonial', 'Plan de sucesión gerencial', 'Inventario de herederos', 'Registro civil de los herederos'],
            '13_DONACIONES_USUFRUCTOS_Y_ESTRUCTURAS_FIDUCIARIAS' => ['Contrato de donación', 'Escritura pública de donación', 'Documento de donación de acciones', 'Documento de donación de inmueble', 'Documento de donación con condiciones', 'Documento de donación con reserva de usufructo', 'Documento de constitución de usufructo', 'Documento de reserva de usufructo', 'Documento de terminación de usufructo', 'Documento de nuda propiedad', 'Fideicomiso civil', 'Contrato de fiducia mercantil', 'Patrimonio autónomo', 'Encargo fiduciario', 'Reglamento fiduciario', 'Certificado de derechos fiduciarios', 'Contrato de administración fiduciaria', 'Documento de instrucciones fiduciarias', 'Informe de la fiduciaria'],
            '15_ADMINISTRACION_REPRESENTACION_Y_PODERES' => ['Poder general', 'Poder especial', 'Autorización para representación de accionista', 'Documento de instrucciones en caso de incapacidad', 'Documento de designación de suplente', 'Acta de nombramiento de representante legal', 'Acta de nombramiento de representante legal suplente', 'Acta de nombramiento de junta directiva', 'Acta de aceptación del cargo', 'Carta de renuncia de administrador', 'Declaración de conflicto de interés', 'Certificado de antecedentes de administradores', 'Informe de gestión del representante legal', 'Reglamento de funciones del representante legal', 'Manual de gobierno corporativo', 'Documento de delegación de funciones', 'Documento de límites de autorización'],
            '16_FAMILIARES_QUE_TRABAJAN_EN_LA_EMPRESA' => ['Contrato laboral de familiar', 'Contrato de prestación de servicios de familiar', 'Descripción del cargo de familiar', 'Manual de funciones de familiar', 'Hoja de vida del familiar', 'Soportes académicos del familiar', 'Evaluación de desempeño de familiar', 'Plan de formación del familiar', 'Plan de carrera del familiar', 'Documento de remuneración del familiar', 'Acuerdo de confidencialidad del familiar', 'Acuerdo de no competencia del familiar', 'Declaración de conflicto de interés del familiar', 'Autorización para operaciones con familiares', 'Documento de retiro del familiar', 'Liquidación laboral del familiar', 'Política de empleo de familiares', 'Política salarial para familiares'],
            '17_CONTRATOS_ENTRE_FAMILIARES_ACCIONISTAS_Y_EMPRESAS' => ['Contrato entre la sociedad y un familiar', 'Contrato de arrendamiento entre familiar y empresa', 'Contrato de préstamo entre familiar y empresa', 'Contrato de compraventa entre familiar y empresa', 'Contrato de prestación de servicios entre familiar y empresa', 'Contrato de mandato entre familiar y empresa', 'Contrato de usufructo entre familiar y empresa', 'Contrato de cesión entre familiar y empresa', 'Documento de cuenta por cobrar a accionista', 'Documento de cuenta por pagar a accionista', 'Autorización de operación con parte relacionada', 'Acta de aprobación de operación con parte relacionada', 'Informe de operaciones con vinculados', 'Estudio de condiciones de mercado', 'Declaración de conflicto de interés'],
            '18_RIESGOS_LITIGIOS_Y_CONTINGENCIAS' => ['Relación de procesos judiciales', 'Relación de procesos administrativos', 'Relación de procesos tributarios', 'Relación de procesos laborales', 'Relación de contingencias', 'Demanda judicial', 'Contestación de demanda', 'Sentencia judicial', 'Acuerdo de conciliación', 'Laudo arbitral', 'Contrato de transacción', 'Documento de embargo', 'Documento de secuestro', 'Documento de medida cautelar', 'Informe de riesgos legales', 'Informe de riesgos societarios', 'Informe de riesgos familiares', 'Informe de riesgos sucesorales', 'Matriz de riesgos familiares', 'Matriz de riesgos societarios', 'Matriz de riesgos sucesorales', 'Plan de tratamiento de riesgos'],
            '19_CONCEPTOS_AUDITORIAS_Y_ASESORIAS_PROFESIONALES' => ['Concepto jurídico societario', 'Concepto jurídico de familia', 'Concepto jurídico sucesoral', 'Concepto tributario', 'Concepto contable', 'Concepto financiero', 'Concepto de valoración', 'Informe de debida diligencia', 'Informe de auditoría jurídica', 'Informe de auditoría societaria', 'Informe de auditoría patrimonial', 'Informe de auditoría contable', 'Informe de auditoría tributaria', 'Informe de auditoría laboral', 'Informe de auditoría de gobierno corporativo', 'Informe de revisión de estatutos', 'Informe de revisión del libro de accionistas', 'Informe de planeación sucesoral', 'Informe de planeación patrimonial'],
            '20_IMPLEMENTACION_Y_CONTROL_DOCUMENTAL' => ['Plan integral de implementación', 'Cronograma de implementación', 'Matriz de implementación jurídica', 'Matriz de responsables', 'Matriz de documentos pendientes', 'Lista de chequeo documental', 'Acta de entrega de documentos', 'Inventario general de documentos', 'Índice del archivo familiar', 'Índice del archivo societario', 'Constancia de inexistencia del documento', 'Documento pendiente de localizar', 'Documento pendiente de actualización', 'Documento no aplicable', 'Solicitud de copia de documento', 'Copia simple del documento', 'Copia auténtica del documento', 'Versión preliminar', 'Versión aprobada', 'Versión firmada', 'Versión registrada', 'Otro documento'],
        ];
    }

    /** @return array<string, list<string>> */
    public static function assetCategories(): array
    {
        return [
            'BIENES_INMUEBLES' => ['Apartamento', 'Casa', 'Local comercial', 'Oficina', 'Consultorio', 'Bodega', 'Lote urbano', 'Lote rural', 'Finca', 'Edificio', 'Parqueadero', 'Depósito', 'Hotel', 'Inmueble industrial', 'Inmueble de uso especial', 'Derecho sobre inmueble', 'Otro inmueble'],
            'ACCIONES_CUOTAS_Y_PARTICIPACIONES_SOCIETARIAS' => ['Acciones ordinarias', 'Acciones privilegiadas', 'Acciones con dividendo preferencial', 'Acciones sin derecho a voto', 'Cuotas sociales', 'Participación en S.A.S.', 'Participación en S.A.', 'Participación en Ltda.', 'Participación en sociedad extranjera', 'Participación indirecta mediante holding', 'Derechos económicos', 'Derechos políticos', 'Nuda propiedad de acciones', 'Usufructo de acciones', 'Otra participación societaria'],
            'INVERSIONES_FINANCIERAS_Y_TITULOS_VALORES' => ['CDT', 'Bono', 'Acción cotizada en bolsa', 'ETF', 'Fondo de inversión colectiva', 'Fondo voluntario de pensiones', 'Encargo fiduciario de inversión', 'Título de deuda privada', 'Título de deuda pública', 'Pagaré de inversión', 'Criptomoneda', 'Depósito a término', 'Cuenta de inversión', 'Otra inversión financiera'],
            'DINERO_EN_CAJA_Y_CUENTAS_BANCARIAS' => ['Caja general', 'Caja menor', 'Cuenta corriente', 'Cuenta de ahorros', 'Cuenta de nómina', 'Cuenta de compensación', 'Cuenta en moneda extranjera', 'Depósito restringido', 'Efectivo en custodia', 'Otra disponibilidad'],
            'CUENTAS_POR_COBRAR_Y_CARTERA' => ['Cartera comercial', 'Cartera de arrendamientos', 'Préstamo a accionista', 'Préstamo a empleado', 'Préstamo a tercero', 'Cuenta por cobrar a vinculada', 'Anticipo a proveedor', 'Cuenta por cobrar judicial', 'Cuenta por cobrar con garantía', 'Intereses por cobrar', 'Honorarios por cobrar', 'Otra cuenta por cobrar'],
            'OTROS_ACTIVOS' => ['Anticipo entregado', 'Depósito en garantía', 'Derecho de recompra', 'Opción de compra', 'Beneficio económico futuro', 'Activo en proceso de identificación', 'Activo contingente', 'Otro activo no clasificado'],
        ];
    }

    public static function code(string $value): string
    {
        $value = strtr($value, ['Á' => 'A', 'É' => 'E', 'Í' => 'I', 'Ó' => 'O', 'Ú' => 'U', 'Ü' => 'U', 'Ñ' => 'N', 'á' => 'A', 'é' => 'E', 'í' => 'I', 'ó' => 'O', 'ú' => 'U', 'ü' => 'U', 'ñ' => 'N']);
        return trim((string) preg_replace('/[^A-Z0-9]+/', '_', strtoupper($value)), '_');
    }
}
